### ISSUE TITLE
Allow manual setting of the pages, filters and sort by field

### ISSUE THREAD

**Issue by mic2100** [reevoo/reevoomark-php-api#11]
Using the API setup that I have means I am unable to use GET vars that are used in the utils class to change the page, filters and sort by data. I would suggest allowing consumers to add these values as options rather that relying on the super global's. I will submit a merge request which will sort this issue and maintain backward compatibility. 

This is how they will be used

``` php
$reevooMark->productReviews(array("sku" => "100A", "paginated" => true, "numberOfReviews" => 10, "page" => 4));
$reevooMark->customerExperienceReviews(array("paginated" => true, "numberOfReviews" => 10, "filter" => "landlord"));
$reevooMark->customerExperienceReviews(array("paginated" => true, "numberOfReviews" => 10, "sort_by" => "recent"));
```

**Comment by mic2100** [comment]
see https://github.com/reevoo/reevoomark-php-api/pull/12

**Comment by errm** [comment]
Hi @mic2100 do you still need this functionality?

**Comment by mic2100** [comment]
This would be nice to have and I'm sure that other developers would also like this because it make it much more flexible.

**Comment by mic2100** [comment]
Package seems to be abandoned!
