### ISSUE TITLE
PHPUnit: unable to mock ReevooMarkApi

### ISSUE THREAD

**Issue by mic2100** [reevoo/reevoomark-php-api#14]
I am unable to mock ReevooMarkApi with PHPUnit because of the additional space before the opening <?php in the reevoo_mark_http_client.php file. 

I get the error: This test printed output:

Is there any chance you can remove this additional space so these classes can be mocked?

**Comment by lpil** [comment]
Hi Michael!

Out of curiosity, how come this space prevents you from mocking ReevooMarkApi? I don't speak PHP.

**Comment by mic2100** [comment]
Basically it outputs the additional space because it is not inside the PHP tags. This causes problems because PHPUnit expects no output when it is running its tests. We can would around this issue but ideally it needs to be fixed.

**Comment by mic2100** [comment]
@lpil Can you also create a new tag for the new revision? v2.2.2

**Comment by lpil** [comment]
Ah, that makes sense. :)

We'll get right on that.

**Comment by reneklacan** [comment]
@mic2100 v2.2.2 has been released

**Comment by mic2100** [comment]
Thanks :)
