### ISSUE TITLE
echo instead of return?

### ISSUE THREAD

**Issue by mic2100** [reevoo/reevoomark-php-api#9]
I am currently working on integrating Reevoo reviews in a website I'm developing on. We have a setup where information is fed to the website from API's so it can be shown to the users. Your library as it stands means we have to do extra work to accommodate for the lack of return values.

Why are you echoing responses? This library would be far more useful if you returned the actual HTML responses and left it up to the developers when they wanted to echo the values out. This also applies the JS and CSS sections which also both echo out the values rather than returning the value for the developer to decide what to do.

```php
<?php $reevooMark->cssAssets() ?>
<?php $css = $reevooMark->cssAssets() ?>
<?= $css?>

<?php $reevooMark->javascriptAssets() ?>
<?php $js = $reevooMark->javascriptAssets() ?>
<?= $js ?>

<?php $reevooMark->productReviews(array("sku" => "100A")) ?>
<?php $reviews = $reevooMark->productReviews(array("sku" => "100A")) ?>
<?= $reviews ?>
```

As you can see converting it to return the value instead of echoing can be easy to migrate and when you have to pass the values between API's it is far easier to handle.

**Comment by errm** [comment]
Hi @mic2100 I have made a quick stab at this over in #10 does this look ok to you?  Not a php person so it could be a bit of a mess . . .
